version: '3.7'

services:
  frontend:
    stdin_open: true
    tty: true
    build: ../frontend
    volumes:
      - "../frontend:/opt/site"
      - "../frontend/node_modules:/opt/site/node_modules"
      - "../frontend/package.json:/opt/site/package.json"
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: on-failure
    depends_on:
      - backend
  backend:
    build: ../backend
    links:
      - "mysql:db"
    ports:
      - "8000:8000"
    volumes:
      - "../backend/src:/opt/site/src"
      - "../backend/test:/opt/site/test"
      - "../backend/package.json:/opt/site/package.json"
    restart: on-failure
    environment:
      HOST_DATABASE: db
      DATABASE: commentsuniverse
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd
      MYSQL_DATABASE: commentsuniverse
      MYSQL_USER: abcd
      MYSQL_PASSWORD: abcd
volumes:
  db_data: {}